<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>第1の謎</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <div class="container">
    <h1>第1の謎</h1>
    <p>Q. 最初に見つけたのは何だった？（ひらがなで答えてください）</p>
    
    <input type="text" id="answer" placeholder="ここに答えを入力">
    <button onclick="checkAnswer()">答える</button>
    <p id="result"></p>
  </div>

  <script>
    function checkAnswer() {
      const input = document.getElementById('answer').value.trim();
      const correct = "ねこ"; // ← 正解をここで指定（例：ねこ）

      if (input === correct) {
        // 正解時に map1.html へ自動遷移
        window.location.href = "map1.html";
      } else {
        document.getElementById('result').textContent = "❌ 不正解。もう一度考えてみてください。";
      }
    }
  </script>
</body>
</html>

